---
- name: print facts
  hosts: all
  #gather_facts: False
  tasks:
    - name: Print OS name
      debug:
        var: ansible_distribution
    - name: Print RAM
      debug:
        var: ansible_memory_mb.real.free
    - name: Print CPU name
      debug:
        var: ansible_processor[2]
