---
- name: understanding vars
  hosts: all
  become: yes
    #vars:
    #USRNM: playusesr
    #COMM: variable from playbook
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{USRNM}}"
        comment: "{{COMM}}"
      register: usrout

    - debug:
        var: usrout.name

    - debug:
        var: usrout.comment
